paths:
  dataset_path: D:\Baagupadu\Datasets\diffusion
  checkpoint_dir: runs\checkpoints

checkpoints:
  best:
    monitor: val_loss
    mode: min
    filename: best
    save_top_k: 1
  latest:
    interval: 10
    filename: latest
    save_top_k: 1

training:
  image_size: 256
  num_timesteps: 1000
  time_embedding_dim: 128
  model_channels:
    - 3
    - 32
    - 64
    - 128
    - 256
  
  # Training parameters
  batch_size: 32
  learning_rate: 0.0001
  epochs: 100
  val_split: 0.1

inference:
  num_samples: 16
  num_inference_steps: 100
  guidance_scale: 1.0